#ifndef SCREENFETCH_VERSION_H
#define SCREENFETCH_VERSION_H

#define SCREENFETCH_VERSION_MAJOR 0
#define SCREENFETCH_VERSION_MINOR 3
#define SCREENFETCH_VERSION_REVISION 3

#endif // SCREENFETCH_VERSION_H
